=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/viewer/src/assets/schemas/Credential-Format.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Credential-Format.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "$ref": "defs.json#/definitions/Schema"
    },
    "Name": {
      "type": "string",
      "description": "Unique identifier of the credential format"
    },
    "Implementation Support": {
      "$ref": "defs.json#/definitions/Implementation-Support"
    },
    "IPR Policy": {
      "$ref": "defs.json#/definitions/IPR-Policy"
    },
    "Specification": {
      "$ref": "defs.json#/definitions/Specification"
    },
    "Standardization (Body, Process)": {
      "$ref": "defs.json#/definitions/Standardization"
    },
    "Encoding Scheme": {
      "type": "string",
      "description": "Data encoding on the storage layer which applies to this credential format",
      "$comment": "can this be set as an enum since the amount of encoding schemes is limited?"
    },
    "Rich Schemas-Semantic": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the credential format able to communicate data or annotations that supports the semantic understanding of the credential data?",
          "$comment": "this sounds like an objective field since semantic is a defined word"
        }
      ]
    },
    "Crypto Agility": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the credential format capable to cover different cryptographic algorithms without any requirements and achieve cryptographic agility, as demanded by regulations?"
        }
      ]
    },
    "Selective Disclosure": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the credential format capable of selective disclosure - presenting or revealing a subset of claims/attributes - without relying on architecture and protocol solutions like Just-in-Time issuance or a presentation transformation by a trusted third party?",
          "$comment": "Do we need to ask if kind of selective disclosure reveals more information like it should? Like using SD-JWT, the verifier can see that the value came from the same credential like in the past, but this is not the case for Anoncreds"
        }
      ]
    },
    "Predicates": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the credential Format able to produce general-purpose predicates, that means attestations without revealing the data, e.g. a proof to be over 18 without revealing the date of birth?"
        }
      ]
    },
    "Compatibility with Signing Algorithms": {
      "type": "string",
      "description": "What signing algorithms can the format be combined with?",
      "$comment": "TBD: https://github.com/openwallet-foundation/credential-format-comparison-sig/issues/44"
    },
    "Compatibility with Key Management Methods (Issuer)": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "What key management methods can the credential format be combined with?",
      "$comment": "TBD: https://github.com/openwallet-foundation/credential-format-comparison-sig/issues/43"
    }
  },
  "required": ["$schema", "Name"],
  "title": "CredentialFormat"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Format/SD-JWT-VC.json
{
  "$schema": "../../schemas/Credential-Format.json",
  "Name": "SD-JWT-VC",
  "IPR Policy": "https://trustee.ietf.org/documents/trust-legal-provisions/",
  "Specification": "https://datatracker.ietf.org/doc/html/draft-terbu-oauth-sd-jwt-vc",
  "Standardization (Body, Process)": "IETF (OAuth WG)",
  "Encoding Scheme": "JSON",
  "Rich Schemas-Semantic": false,
  "Crypto Agility": true,
  "Selective Disclosure": true,
  "Predicates": false,
  "Compatibility with Signing Algorithms": "ECDSA, EdDSA, RSA",
  "Compatibility with Key Management Methods (Issuer)": [
    "did:key",
    "did:web",
    "did:ebsi",
    "did:iota",
    "did:jwk",
    "did:cheqd",
    "did:velocity"
  ]
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Format/Idemix-attribute-based-credential.json
{
  "$schema": "../../schemas/Credential-Format.json",
  "Name": "Idemix attribute-based credential",
  "Implementation Support": "https://github.com/privacybydesign/gabi (cryptography), https://github.com/privacybydesign/irmago (semantics, wallet, servers, more)",
  "Specification": "None. Protocol documented here: https://irma.app/docs/irma-protocol",
  "Standardization (Body, Process)": "Privacy by Design Foundation",
  "Encoding Scheme": "JSON",
  "Rich Schemas-Semantic": true,
  "Crypto Agility": {
    "Value": false,
    "Description": "only Idemix support"
  },
  "Selective Disclosure": true,
  "Predicates": true,
  "Compatibility with Signing Algorithms": "CL",
  "Compatibility with Key Management Methods (Issuer)": [
    "raw public keys (none jwk)"
  ]
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Format/VC-(1.1).json
{
  "$schema": "../../schemas/Credential-Format.json",
  "Name": "VC (1.1)",
  "Implementation Support": "https://jwt.io/libraries",
  "IPR Policy": "https://www.w3.org/Consortium/Patent-Policy-20200915/#sec-Requirements",
  "Specification": "https://www.w3.org/TR/vc-data-model/",
  "Standardization (Body, Process)": "W3C",
  "Encoding Scheme": "JSON, JSON-LD",
  "Rich Schemas-Semantic": true,
  "Crypto Agility": true,
  "Selective Disclosure": true,
  "Predicates": false,
  "Compatibility with Signing Algorithms": "ECDSA, EdDSA, RSA",
  "Compatibility with Key Management Methods (Issuer)": ["x509", "did methods"]
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Format/ACDC-(KERI).json
{
  "$schema": "../../schemas/Credential-Format.json",
  "Name": "ACDC",
  "Specification": "https://trustoverip.github.io/tswg-acdc-specification/",
  "Standardization (Body, Process)": "",
  "Encoding Scheme": "CESR",
  "Rich Schemas-Semantic": false,
  "Crypto Agility": true,
  "Selective Disclosure": true,
  "Predicates": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Format/LDP-VC.json
{
  "$schema": "../../schemas/Credential-Format.json",
  "Name": "LDP-VC",
  "Implementation Support": "https://github.com/digitalbazaar/jsonld.js",
  "IPR Policy": "https://www.w3.org/Consortium/Patent-Policy-20200915/#sec-Requirements",
  "Specification": "https://www.w3.org/TR/vc-data-model/",
  "Standardization (Body, Process)": "W3C",
  "Encoding Scheme": "JSON-LD",
  "Rich Schemas-Semantic": true,
  "Crypto Agility": true,
  "Selective Disclosure": {
    "Value": true,
    "Description": "BBS\nCL-Signatures (CL)\nShort Randomizable Signatures (ps-sig)"
  },
  "Predicates": {
    "Value": true,
    "Description": "depending on signature algorithm"
  },
  "Compatibility with Signing Algorithms": "ECDSA, EdDSA, RSA",
  "Compatibility with Key Management Methods (Issuer)": [
    "did:key",
    "did:web",
    "did:ebsi",
    "did:iota",
    "did:jwk",
    "did:cheqd",
    "did:velocity"
  ]
}
