=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/viewer/src/assets/schemas/Signing-Algorithm.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Signing-Algorithm.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "$ref": "defs.json#/definitions/Schema"
    },
    "Name": {
      "type": "string",
      "description": "A unique identifier for the signing algorithm"
    },
    "Implementation Support": {
      "$ref": "defs.json#/definitions/Implementation-Support"
    },
    "IPR Policy": {
      "$ref": "defs.json#/definitions/IPR-Policy"
    },
    "Specification": {
      "$ref": "defs.json#/definitions/Specification"
    },
    "Standardization (Body, Process)": {
      "$ref": "defs.json#/definitions/Standardization"
    },
    "Recognition by government authorities (NIST, BSI, ...)": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the signing algorithm recognized in regulatory frameworks of leading government bodies?"
        }
      ]
    },
    "Performance": {
      "type": "string",
      "description": "How performant is the signing algorithm?",
      "$comment": "difficult to answer, since there is no performance framework to measure against"
    },
    "Hardware support": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the Signing Algorithm supported by common hardware-backed cryptographic implementations, such as Secure Elements, SecureEnclave, HSM, Strongbox, TEE, TPM",
          "$comment": "Using different approaches can lead to different results when choosing key lengths or performance measurements"
        }
      ]
    },
    "Unlinkability-Uncorrelatability-Blind signatures possible": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the Signing Algorithm capable of creating a credential scheme, such that two verification processes can not be linked/correlated by colluding Verifiers/Relying Parties?"
        }
      ]
    },
    "Security strength": {
      "type": "string",
      "description": "What level of security strength is common and standardized for this signing algorithm?"
    },
    "Post-quantum security": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the Signing Algorithm still secure if quantum computing achieves substantial computation power?"
        }
      ]
    }
  },
  "required": ["$schema", "Name"],
  "title": "SigningAlgorithm"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Signing-Algorithm/BBS+-with-public-key-binding.json
{
  "$schema": "../../schemas/Signing-Algorithm.json",
  "Name": "BBS+ with public key binding",
  "Implementation Support": "https://github.com/mattrglobal/bbs-signatures",
  "Specification": "https://datatracker.ietf.org/doc/draft-looker-cfrg-bbs-signatures/",
  "Standardization (Body, Process)": "DIF (intention to transfer to IRTF CFRG)",
  "Recognition by government authorities (NIST, BSI, ...)": {
    "Value": false,
    "Description": "not acknowledged"
  },
  "Hardware support": false,
  "Unlinkability-Uncorrelatability-Blind signatures possible": false,
  "Security strength": "381 bit curve",
  "Post-quantum security": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Signing-Algorithm/EdDSA.json
{
  "$schema": "../../schemas/Signing-Algorithm.json",
  "Name": "EdDSA",
  "Implementation Support": "many mature implementations",
  "Recognition by government authorities (NIST, BSI, ...)": {
    "Value": true,
    "Description": "widely accepted, though still behind ECDSA"
  },
  "Performance": "high",
  "Hardware support": false,
  "Unlinkability-Uncorrelatability-Blind signatures possible": false,
  "Security strength": "257 / 384 / 512 bit",
  "Post-quantum security": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Signing-Algorithm/BoundBBS+.json
{
  "$schema": "../../schemas/Signing-Algorithm.json",
  "Name": "BoundBBS+",
  "IPR Policy": "barely",
  "Standardization (Body, Process)": "DIF (intention to transfer to IRTF CFRG)",
  "Recognition by government authorities (NIST, BSI, ...)": {
    "Value": false,
    "Description": "not acknowledged"
  },
  "Hardware support": false,
  "Unlinkability-Uncorrelatability-Blind signatures possible": true,
  "Post-quantum security": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Signing-Algorithm/Schnorr.json
{
  "$schema": "../../schemas/Signing-Algorithm.json",
  "Name": "Schnorr",
  "Implementation Support": "many mature implementations",
  "IPR Policy": "patents expired",
  "Specification": "different curves-different specs",
  "Standardization (Body, Process)": "different curves-different standards",
  "Recognition by government authorities (NIST, BSI, ...)": {
    "Value": true,
    "Description": "NIST with Curve25519"
  },
  "Performance": "high",
  "Hardware support": false,
  "Unlinkability-Uncorrelatability-Blind signatures possible": false,
  "Post-quantum security": false
}
