=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/viewer/src/assets/schemas/Status-Algorithm.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Status-Algorithm.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "$ref": "defs.json#/definitions/Schema"
    },
    "Name": {
      "type": "string",
      "description": "Unique identifier of the algorithm"
    },
    "Implementation Support": {
      "$ref": "defs.json#/definitions/Implementation-Support"
    },
    "IPR Policy": {
      "$ref": "defs.json#/definitions/IPR-Policy"
    },
    "Specification": {
      "$ref": "defs.json#/definitions/Specification"
    },
    "Standardization (Body, Process)": {
      "$ref": "defs.json#/definitions/Standardization"
    },
    "Recognition by government authorities (NIST, BSI, ...)": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is the status algorithm recognized in regulatory frameworks of leading government bodies?"
        }
      ]
    },
    "Category": {
      "type": "string",
      "description": "Algorithm that behind the implementation of the revocation (Bitlist = each credential has a position in the list. Deny-List: revoked credentials will be added on demand. Accumulator: cryptographic proof the holder presents to show that the credential is not revoked)"
    },
    "Performance": {
      "type": "string",
      "description": "How performant is the revocation mechanism (for issuer, holder and verifier)?",
      "$comment": "For this case there could be some king of test framework"
    },
    "Observability": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Does the Verifier have the possibility to observe the revocation status beyond the presentation?"
        }
      ]
    },
    "Traceability": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Does the issuer have possibilities to trace the usage of his issued credentials through the revocation mechanism?",
          "$comment": "With a size of one used element the issuer should always be able to trace the usage of his issued credentials"
        }
      ]
    },
    "Scalability": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "At what scale has the algorithm/technology been demonstrated to work? Are there any known issues?"
        }
      ]
    },
    "Offline Friendliness": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Does the revocation mechanism support an authentication if the holder is offline?"
        }
      ]
    }
  },
  "required": ["$schema", "Name"],
  "title": "RevocationAlgorithm"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Status-Algorithm/JWT-CWT-status-list.json
{
  "$schema": "../../schemas/Status-Algorithm.json",
  "Name": "JWT/CWT status list",
  "Implementation Support": "https://github.com/vcstuff/draft-looker-oauth-jwt-cwt-status-list",
  "Specification": "https://datatracker.ietf.org/doc/draft-terbu-oauth-sd-jwt-vc/",
  "Standardization (Body, Process)": "IETF Individual",
  "Recognition by government authorities (NIST, BSI, ...)": false,
  "Category": "Bitstring",
  "Observability": true,
  "Traceability": {
    "Value": true,
    "Description": "potentially possible with malicious issuer by providing a revocation list with a single entry"
  }
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Status-Algorithm/RSA-B-cryptographic-accumulator-based-on-RSA.json
{
  "$schema": "../../schemas/Status-Algorithm.json",
  "Name": "RSA-B - cryptographic accumulator based on RSA",
  "Implementation Support": "https://github.com/privacybydesign/gabi/tree/master/revocation",
  "Specification": "https://eprint.iacr.org/2017/043.pdf",
  "Recognition by government authorities (NIST, BSI, ...)": false,
  "Category": "Accumulator",
  "Observability": true,
  "Traceability": false,
  "Offline Friendliness": true
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Status-Algorithm/Status-List-2021.json
{
  "$schema": "../../schemas/Status-Algorithm.json",
  "Name": "Status List 2021",
  "Implementation Support": "https://github.com/transmute-industries/verifiable-data/tree/main/packages/vc-status-rl-2020",
  "Specification": "https://w3c-ccg.github.io/vc-status-list-2021/",
  "Standardization (Body, Process)": "W3C",
  "Recognition by government authorities (NIST, BSI, ...)": false,
  "Category": "Bitstring",
  "Observability": true,
  "Traceability": {
    "Value": true,
    "Description": "potentially possible with malicious issuer by providing a revocation list with a single entry"
  }
}
