=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/viewer/src/assets/schemas/Trust-Management.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Trust-Management.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "$ref": "defs.json#/definitions/Schema"
    },
    "Name": {
      "type": "string",
      "description": "A unique identifier for the trust management approach"
    },
    "Implementation Support": {
      "$ref": "defs.json#/definitions/Implementation-Support"
    },
    "IPR Policy": {
      "$ref": "defs.json#/definitions/IPR-Policy"
    },
    "Standardization (Body, Process)": {
      "$ref": "defs.json#/definitions/Standardization"
    },
    "Specification": {
      "$ref": "defs.json#/definitions/Specification"
    },
    "Description": {
      "type": "string",
      "description": "Explanation or link to a source how this trust management approach works"
    }
  },
  "required": ["$schema", "Name"],
  "title": "TrustManagement"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Trust-Management/OpenID-Connect-Federation.json
{
  "$schema": "../../schemas/Trust-Management.json",
  "Name": "OpenID Connect Federation",
  "Standardization (Body, Process)": "OpenID Foundation",
  "Specification": "https://openid.net/specs/openid-connect-federation-1_0.html",
  "Description": "Uses JWTs and REST APIs to represent trust chains and trust marks"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Trust-Management/Trusted-Lists.json
{
  "$schema": "../../schemas/Trust-Management.json",
  "Name": "Trusted Lists",
  "Standardization (Body, Process)": "ETSi",
  "Specification": "https://www.etsi.org/deliver/etsi_ts/119600_119699/119612/02.02.01_60/ts_119612v020201p.pdf",
  "Description": "used by EU Trusted List (https://webgate.ec.europa.eu/tl-browser/)"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Trust-Management/Verifier-knows-Issuers.json
{
  "$schema": "../../schemas/Trust-Management.json",
  "Name": "Verifier knows Issuers",
  "Implementation Support": "Manual / bespoke",
  "IPR Policy": "None",
  "Standardization (Body, Process)": "None",
  "Specification": "None",
  "Description": "The verifier knows which issuers he trusts for issuing certain credentials, organizational solution"
}
