=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/viewer/src/assets/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "CredentialAgent",
  "title": "Credential Agent",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version of the agent JSON entry"
    },
    "name": {
      "type": "string",
      "description": "The name of the agent"
    },
    "urlWebsite": {
      "type": "string",
      "description": "An URL to the website of the agent with more information",
      "format": "uri"
    },
    "logo": {
      "type": "string",
      "description": "The URL to the logo of the agent"
    },
    "company": {
      "type": "string",
      "description": "The name of the company or a community developing the agent"
    },
    "companyUrl": {
      "type": "string",
      "description": "The url to the company website (not the product website)",
      "format": "uri"
    },
    "contact": {
      "type": "string",
      "description": "A link to a contact form or an email address for support requests"
    },
    "openSource": {
      "type": "boolean",
      "description": "The agent source code is available under an open-source license"
    },
    "downloadSource": {
      "type": "string",
      "description": "The URL to the source code, for example a github repository",
      "format": "uri"
    },
    "license": {
      "type": "string",
      "description": "The license(s) of the agent source code."
    },
    "capability": {
      "type": "array",
      "description": "The capabilities supported by the agent",
      "items": {
        "type": "string",
        "enum": ["holder", "issuer", "verifier"]
      }
    },
    "type": {
      "type": "string",
      "description": "The deployment model of the agent (e.g., cloud service or mobile app)",
      "enum": ["cloud", "mobile"]
    },
    "portability": {
      "type": "boolean",
      "description": "Users can export their data from the agent and import them into another device/system"
    },
    "urlAppStore": {
      "type": "string",
      "description": "Link to the Apple AppStore",
      "format": "uri"
    },
    "urlGooglePlayStore": {
      "type": "string",
      "description": "link to the Google Play store",
      "format": "uri"
    },
    "urlWebApp": {
      "type": "string",
      "description": "Link to the web app - where the agent can be used with a browser",
      "format": "uri"
    },
    "credentialProfiles": {
      "type": "array",
      "description": "list of supported credential profiles, it has to be a valid credential profile from the Credential Profiles Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Credential-Profile"
      }
    },
    "credentialFormats": {
      "type": "array",
      "description": "list of supported credential formats, it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Credential%20Format",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Credential-Format"
      }
    },
    "signingAlgorithms": {
      "type": "array",
      "description": "list of supported signing algorithms, it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Signing%20Algorithm",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Signing-Algorithm"
      }
    },
    "statusManagements": {
      "type": "array",
      "description": "list of supported status algorithms, it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Status%20Algorithm",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Status-Algorithm"
      }
    },
    "keyManagements": {
      "type": "array",
      "description": "list of supported key managements, it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Key%20Management",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Key-Management"
      }
    },
    "issuanceProtocols": {
      "type": "array",
      "description": "list of supported issuance protocols , it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Issuance%20Protocol",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Issuance-Protocol"
      }
    },
    "presentationProtocols": {
      "type": "array",
      "description": "list of supported presentation protocols , it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Presentation%20Protocol",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Presentation-Protocol"
      }
    },
    "trustManagements": {
      "type": "array",
      "description": "list of supported trust managements , it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Trust%20Management",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Trust-Management"
      }
    }
  },
  "required": ["capability", "company", "name", "urlWebsite"],
  "additionalProperties": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/Data Wallet.json
{
  "capability": ["holder"],
  "company": "iGrant.io",
  "credentialFormats": ["AnonCred"],
  "credentialProfiles": ["AnonCreds with did:indy", "EBSI", "ICAO DTC", "x.509"],
  "issuanceProtocols": ["OpenID4VCI", "Issue Credential v2"],
  "keyManagements": ["did:ebsi", "did:key", "pub key in X.509 cert"],
  "logo": "logos/data-wallet.png",
  "name": "Data Wallet",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../viewer/src/assets/schema.json",
  "signingAlgorithms": ["CL", "ECDSA"],
  "statusManagements": ["Indy Revocation", "Status List 2021"],
  "type": "mobile",
  "urlAppStore": "https://apple.co/2Mz9nJp",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=io.igrant.mobileagent",
  "urlWebApp": "https://business.igrant.io/",
  "urlWebsite": "https://igrant.io/datawallet.html"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/KayTrust Wallet.json
{
  "capability": ["holder"],
  "company": "KayTrust",
  "contact": "did@emeal.nttdata.com",
  "logo": "logos/kaytrust-wallet.png",
  "name": "KayTrust Wallet",
  "openSource": false,
  "$schema": "../viewer/src/assets/schema.json",
  "type": "mobile",
  "urlAppStore": "https://apps.apple.com/us/app/mytrust-wallet/id1477073898",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=com.everis.mytrust.app",
  "urlWebsite": "https://kaytrust.id/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/Gataca Studio.json
{
  "capability": ["issuer", "verifier"],
  "company": "Gataca Inc.",
  "credentialFormats": ["LDP-VC", "JWT-VC"],
  "credentialProfiles": ["EBSI"],
  "issuanceProtocols": ["OpenID4VCI"],
  "keyManagements": ["did:key"],
  "logo": "logos/gataca.png",
  "name": "Gataca Studio",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../viewer/src/assets/schema.json",
  "signingAlgorithms": ["EdDSA", "RSA"],
  "type": "cloud",
  "urlWebsite": "https://gataca.io/products/gatacaStudio/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/Vidua.json
{
  "capability": ["holder"],
  "company": "Cleverbase",
  "credentialFormats": ["x509", "JWT"],
  "contact": "klantenservice@vidua.nl",
  "issuanceProtocols": ["OpenID4VCI"],
  "logo": "logos/vidua.png",
  "name": "Vidua",
  "openSource": false,
  "portability": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../viewer/src/assets/schema.json",
  "signingAlgorithms": ["ECDSA", "RSA"],
  "type": "mobile",
  "urlAppStore": "https://apps.apple.com/en/app/vidua/id6443842104",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=nl.vidua.wallet",
  "urlWebsite": "https://vidua.nl/english/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/MYKEEPiN.json
{
  "capability": ["holder"],
  "company": "Metadium Technology Inc",
  "credentialFormats": ["JWT", "JWT-VC"],
  "logo": "logos/mykeepin.png",
  "name": "Wepublic",
  "$schema": "../viewer/src/assets/schema.json",
  "signingAlgorithms": ["ECDSA"],
  "type": "mobile",
  "urlWebsite": "https://metadium.com/Portfolio/DApp/Wallet",
  "urlAppStore": "https://apps.apple.com/kr/app/mykeepin-%EC%BD%94%EC%9D%B8%ED%94%8C%EB%9F%AC%EA%B7%B8-%EB%94%94%EC%A7%80%ED%84%B8-id/id1479166844",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=com.coinplug.mykeepin"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/Orbit Edge Wallet.json
{
  "capability": ["holder"],
  "company": "Northern Block",
  "contact": "info@northernblock.io",
  "logo": "https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/dd/22/09/dd220977-1f77-b23c-a624-5d6e1574a159/AppIcon-0-0-1x_U007emarketing-0-5-0-85-220.png/230x0w.webp",
  "name": "Orbit Edge Wallet",
  "$schema": "../viewer/src/assets/schema.json",
  "type": "mobile",
  "urlAppStore": "https://apps.apple.com/us/app/orbit-edge/id1508037063",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=com.northernblock",
  "urlWebsite": "https://northernblock.io/orbit-edge-wallet/"
}
