=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/viewer/src/assets/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "CredentialAgent",
  "title": "Credential Agent",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version of the agent JSON entry"
    },
    "name": {
      "type": "string",
      "description": "The name of the agent"
    },
    "urlWebsite": {
      "type": "string",
      "description": "An URL to the website of the agent with more information",
      "format": "uri"
    },
    "logo": {
      "type": "string",
      "description": "The URL to the logo of the agent"
    },
    "company": {
      "type": "string",
      "description": "The name of the company or a community developing the agent"
    },
    "companyUrl": {
      "type": "string",
      "description": "The url to the company website (not the product website)",
      "format": "uri"
    },
    "contact": {
      "type": "string",
      "description": "A link to a contact form or an email address for support requests"
    },
    "openSource": {
      "type": "boolean",
      "description": "The agent source code is available under an open-source license"
    },
    "downloadSource": {
      "type": "string",
      "description": "The URL to the source code, for example a github repository",
      "format": "uri"
    },
    "license": {
      "type": "string",
      "description": "The license(s) of the agent source code."
    },
    "capability": {
      "type": "array",
      "description": "The capabilities supported by the agent",
      "items": {
        "type": "string",
        "enum": ["holder", "issuer", "verifier"]
      }
    },
    "type": {
      "type": "string",
      "description": "The deployment model of the agent (e.g., cloud service or mobile app)",
      "enum": ["cloud", "mobile"]
    },
    "portability": {
      "type": "boolean",
      "description": "Users can export their data from the agent and import them into another device/system"
    },
    "urlAppStore": {
      "type": "string",
      "description": "Link to the Apple AppStore",
      "format": "uri"
    },
    "urlGooglePlayStore": {
      "type": "string",
      "description": "link to the Google Play store",
      "format": "uri"
    },
    "urlWebApp": {
      "type": "string",
      "description": "Link to the web app - where the agent can be used with a browser",
      "format": "uri"
    },
    "credentialProfiles": {
      "type": "array",
      "description": "list of supported credential profiles, it has to be a valid credential profile from the Credential Profiles Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Credential-Profile"
      }
    },
    "credentialFormats": {
      "type": "array",
      "description": "list of supported credential formats, it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Credential%20Format",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Credential-Format"
      }
    },
    "signingAlgorithms": {
      "type": "array",
      "description": "list of supported signing algorithms, it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Signing%20Algorithm",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Signing-Algorithm"
      }
    },
    "statusManagements": {
      "type": "array",
      "description": "list of supported status algorithms, it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Status%20Algorithm",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Status-Algorithm"
      }
    },
    "keyManagements": {
      "type": "array",
      "description": "list of supported key managements, it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Key%20Management",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Key-Management"
      }
    },
    "issuanceProtocols": {
      "type": "array",
      "description": "list of supported issuance protocols , it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Issuance%20Protocol",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Issuance-Protocol"
      }
    },
    "presentationProtocols": {
      "type": "array",
      "description": "list of supported presentation protocols , it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Presentation%20Protocol",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Presentation-Protocol"
      }
    },
    "trustManagements": {
      "type": "array",
      "description": "list of supported trust managements , it has to be a valid credential format from the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Trust%20Management",
      "items": {
        "$ref": "https://openwallet-foundation.github.io/credential-format-comparison-sig/assets/schemas/fields.json#/definitions/Trust-Management"
      }
    }
  },
  "required": ["capability", "company", "name", "urlWebsite"],
  "additionalProperties": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/Identry.json
{
  "capability": ["issuer", "holder", "verifier"],
  "company": "Identry",
  "credentialFormats": ["AnonCred"],
  "credentialProfiles": ["AnonCreds with did:indy"],
  "logo": "logos/identry.png",
  "name": "Identry",
  "openSource": false,
  "$schema": "../viewer/src/assets/schema.json",
  "signingAlgorithms": ["CL"],
  "urlAppStore": "https://apps.apple.com/us/app/identry/id1609224919",
  "urlWebsite": "https://identry.io/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/Talao.json
{
  "capability": ["holder"],
  "company": "Talao",
  "credentialFormats": ["JWT-VC", "LDP-VC"],
  "credentialProfiles": ["EBSI"],
  "downloadSource": "https://github.com/TalaoDAO/talao-wallet",
  "issuanceProtocols": ["OpenID4VCI"],
  "keyManagements": ["did:ebsi", "did:web", "did:key"],
  "license": "Apache 2.0",
  "logo": "logos/talao.png",
  "name": "Talao Wallet",
  "openSource": true,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../viewer/src/assets/schema.json",
  "signingAlgorithms": ["ECDSA"],
  "statusManagements": ["Status List 2021"],
  "type": "mobile",
  "urlAppStore": "https://apps.apple.com/app/talao-wallet/id1582183266#?platform=iphone",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=co.talao.wallet",
  "urlWebsite": "https://talao.io/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/SelfKey Wallet.json
{
  "capability": ["holder"],
  "company": "SelfKey",
  "downloadSource": "https://github.com/SelfKeyFoundation/Identity-Wallet",
  "logo": "https://selfkey.org/wp-content/uploads/2023/03/image-1.png",
  "name": "SelfKey Wallet",
  "$schema": "../viewer/src/assets/schema.json",
  "type": "mobile",
  "urlAppStore": "https://selfkey.org/selfkey-wallet-ios-download",
  "urlGooglePlayStore": "https://selfkey.org/selfkey-wallet-android-download",
  "urlWebsite": "https://selfkey.org/selfkey-wallet/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/Trisic ID.json
{
  "capability": ["holder"],
  "company": "Trinsic",
  "downloadSource": "https://github.com/trinsic-id/wallet-reference-app",
  "logo": "https://ml58lemqnh9a.i.optimole.com/cb:Xgnl.4ea3/w:404/h:116/q:100/f:best/https://trinsic.id/wp-content/uploads/2023/03/Logo-Blue-1024x299.png.png",
  "name": "Trinsic ID",
  "openSource": true,
  "$schema": "../viewer/src/assets/schema.json",
  "type": "mobile",
  "urlAppStore": "https://apps.apple.com/us/app/trinsic-id/id1475160728",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=id.streetcred.apps.mobile",
  "urlWebsite": "https://trinsic.id/an-introduction-to-the-trinsic-wallet/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/Datakeeper.json
{
  "capability": ["holder"],
  "company": "Datakeeper Wallet",
  "credentialFormats": ["LDP-VC"],
  "logo": "logos/datakeeper.png",
  "name": "Datakeeper",
  "openSource": false,
  "$schema": "../viewer/src/assets/schema.json",
  "signingAlgorithms": ["ECDSA"],
  "urlAppStore": "https://apps.apple.com/nl/app/datakeeper/id1546059184",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=nl.rabobank.ida&gl=US",
  "urlWebsite": "https://www.datakeeper.nl/en"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/helix id.json
{
  "capability": ["holder"],
  "company": "Blockchain Helix AG",
  "credentialFormats": ["JWT", "JWT-VC"],
  "issuanceProtocols": ["OpenID4VCI", "Issue Credential v2"],
  "keyManagements": ["did:key"],
  "logo": "logos/helix-id.png",
  "name": "helix id",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../viewer/src/assets/schema.json",
  "signingAlgorithms": ["BBS+ with public key binding", "ECDSA"],
  "type": "mobile",
  "urlAppStore": "https://apps.apple.com/de/app/helix-id-wallet/id1469238013",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=com.io.helix.id",
  "urlWebsite": "https://helixid.io/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/Gataca.json
{
  "capability": ["holder"],
  "company": "Gataca Inc.",
  "credentialFormats": ["LDP-VC", "JWT-VC"],
  "credentialProfiles": ["EBSI"],
  "issuanceProtocols": ["OpenID4VCI"],
  "keyManagements": ["did:key"],
  "logo": "logos/gataca.png",
  "name": "Gataca Wallet",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../viewer/src/assets/schema.json",
  "signingAlgorithms": ["EdDSA", "RSA"],
  "type": "mobile",
  "urlAppStore": "https://apps.apple.com/us/app/gataca/id1498607616",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=com.gataca.identity",
  "urlWebsite": "https://gataca.io/products/wallet/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/wallets/Microsoft Entra.json
{
  "capability": ["issuer", "verifier"],
  "company": "Microsoft",
  "credentialFormats": ["JWT-VC"],
  "keyManagements": ["did:web"],
  "logo": "logos/microsoft-entra.png",
  "name": "Microsoft Entra Verified ID",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../viewer/src/assets/schema.json",
  "type": "cloud",
  "urlWebsite": "https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-verified-id"
}
