=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/schemas/credential-profile.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "CredentialProfile",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "$ref": "defs.json#/definitions/Schema"
    },
    "Name": {
      "type": "string",
      "description": "The name of the credential profile, as it is commonly called.  This is the name that should be used to refer to the credential profile in other documents and discussions"
    },
    "Credential Profile Description": {
      "type": "string",
      "description": "A brief description of the credential profile"
    },
    "Credential Format": {
      "type": "string",
      "description": "The format of the credential."
    },
    "Signing Algorithm": {
      "type": "string",
      "description": "The format of the signing algorithm."
    },
    "Status Algorithm": {
      "type": "string",
      "description": "The format of the status algorithm."
    },
    "Key Management (Issuer)": {
      "type": "string",
      "description": "The format of the key management for the issuer."
    },
    "Key Management (Holder)": {
      "type": "string",
      "description": "The format of the key management for the holder."
    },
    "Issuance Protocol": {
      "type": "string",
      "description": "The format of issuance protocol."
    },
    "Presentation Protocol": {
      "type": "string",
      "description": "The format of the presentation protocol."
    },
    "Trust Management": {
      "type": "string",
      "description": "The format of the trust management."
    },
    "Formal Specification": {
      "type": "string",
      "description": "A link to a formal specification of the credential profile."
    }
  },
  "required": [
    "$schema",
    "Credential Format",
    "Credential Profile Description",
    "Name",
    "Key Management (Holder)",
    "Key Management (Issuer)",
    "Signing Algorithm"
  ],
  "title": "CredentialProfile"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Profile/DIIP.json
{
  "$schema": "../../schemas/Credential-Profile.json",
  "Name": "Decentralized Identity Interop Profile",
  "Formal Specification": "https://dutchblockchaincoalition.github.io/DIIP/",
  "Credential Profile Description": "Decentralized Identity Interop Profile",
  "Credential Format": "JWT-VC",
  "Signing Algorithm": "ECDSA",
  "Status Algorithm": "Status List 2021",
  "Key Management (Issuer)": "did:web",
  "Key Management (Holder)": "did:jwk",
  "Issuance Protocol": "OpenID4VCI",
  "Presentation Protocol": "OpenID4VP"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Profile/AnonCreds-web.json
{
  "$schema": "../../schemas/Credential-Profile.json",
  "Name": "AnonCreds with did:web",
  "Credential Profile Description": "AnonCreds with did:web",
  "Credential Format": "AnonCred",
  "Signing Algorithm": "CL",
  "Status Algorithm": "Indy Revocation",
  "Key Management (Issuer)": "did:web",
  "Key Management (Holder)": "link secrets",
  "Trust Management": "Verifier knows Issuers",
  "Formal Specification": "https://github.com/2060-io/did-web-anoncreds-method"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Profile/NGI-Atlantic-for-OpenID4VCs.json
{
  "$schema": "../../schemas/Credential-Profile.json",
  "Name": "NGI Atlantic for OpenID4VCs",
  "Credential Profile Description": "https://ngiatlantic.info\nhttps://ngiatlantic.eu/funded-experiments/next-generation-ssi-standards",
  "Credential Format": "JWT-VC",
  "Signing Algorithm": "ECDSA",
  "Status Algorithm": "short-term expiration",
  "Key Management (Issuer)": "did:key",
  "Key Management (Holder)": "did:key",
  "Trust Management": "TRAIN",
  "Formal Specification": "https://ngiatlantic.info"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Profile/IRMA-(Yivi)-wallet.json
{
  "$schema": "../../schemas/Credential-Profile.json",
  "Name": "IRMA (Yivi) wallet",
  "Credential Profile Description": "https://dominoweb.draco.res.ibm.com/reports/rz3730_revised.pdf",
  "Credential Format": "Idemix attribute-based credential",
  "Signing Algorithm": "CL",
  "Status Algorithm": "RSA-B - cryptographic accumulator based on RSA",
  "Key Management (Issuer)": "raw public keys (none jwk)",
  "Key Management (Holder)": "link secrets",
  "Trust Management": "IRMA (Yivi) Schemes"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Profile/AnonCreds-indy.json
{
  "$schema": "../../schemas/Credential-Profile.json",
  "Name": "AnonCreds with did:indy",
  "Credential Profile Description": "Well-known default profile in all Hyperledger Indy implementations. A favoured profile due to selective disclosure and predicate capability as well as privacy-preserving revocation mechanism. Standardization in community spec in progress (July 2022).",
  "Credential Format": "AnonCred",
  "Signing Algorithm": "CL",
  "Status Algorithm": "Indy Revocation",
  "Key Management (Issuer)": "did:indy",
  "Key Management (Holder)": "link secrets",
  "Trust Management": "Verifier knows Issuers",
  "Formal Specification": "https://hyperledger.github.io/anoncreds-spec/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Profile/JSON-LD-VCs-with-BBS-(Credential-is-Secret).json
{
  "$schema": "../../schemas/Credential-Profile.json",
  "Name": "JSON-LD VCs with BBS (Credential is Secret)",
  "Credential Profile Description": "[Profile description goes here]",
  "Credential Format": "LDP-VC",
  "Signing Algorithm": "BoundBBS+",
  "Status Algorithm": "Status List 2021",
  "Key Management (Issuer)": "did:web",
  "Key Management (Holder)": "credential as secret"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Profile/JSON-LD-VCs-with-BBS-(Holder-DID).json
{
  "$schema": "../../schemas/Credential-Profile.json",
  "Name": "JSON-LD VCs with BBS (Holder DID)",
  "Credential Profile Description": "[Profile description goes here]",
  "Credential Format": "LDP-VC",
  "Signing Algorithm": "BBS+ with public key binding",
  "Status Algorithm": "Status List 2021",
  "Key Management (Issuer)": "did:web",
  "Key Management (Holder)": "did:key"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Credential-Profile/JWT-VC-Presentation-Profile.json
{
  "$schema": "../../schemas/Credential-Profile.json",
  "Name": "JWT VC Presentation Profile",
  "Credential Profile Description": "https://identity.foundation/jwt-vc-presentation-profile/",
  "Credential Format": "JWT-VC",
  "Signing Algorithm": "ECDSA",
  "Status Algorithm": "Status List 2021",
  "Key Management (Issuer)": "did:ion (long form)",
  "Key Management (Holder)": "did:ion (long form)"
}
