=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/schemas/Key-Management.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Key-Management.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "$ref": "defs.json#/definitions/Schema"
    },
    "Name": {
      "type": "string",
      "description": "Unique identifier of the method"
    },
    "Implementation Support": {
      "$ref": "defs.json#/definitions/Implementation-Support"
    },
    "IPR Policy": {
      "$ref": "defs.json#/definitions/IPR-Policy"
    },
    "Specification": {
      "$ref": "defs.json#/definitions/Specification"
    },
    "Infrastructure for Key Resolution": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is there any infrastructure required to resolve keys and/or validate identifier to key binding?"
        }
      ]
    },
    "Key Rotation": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Can the key referred to in a credential be replaced by another key?"
        }
      ]
    },
    "Key History": {
      "allOf": [
        {
          "$ref": "defs.json#/definitions/Filter"
        },
        {
          "description": "Is it possible to retain and obtain the history of keys related to a certain identifier? In case of key rotation it is important for signed credentials to request older keys that are not used for signing anymore"
        }
      ]
    },
    "Party": {
      "type": "array",
      "items": {
        "enum": ["issuer", "holder"]
      },
      "description": "What party may uses this technique?",
      "$comment": "We are not looking at verifiers here, since e.g. the identification of the verifier is not part of the credential comparison matrix"
    }
  },
  "required": ["$schema", "Name"],
  "title": "KeyManagement"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Key-Management/did.keri.json
{
  "$schema": "../../schemas/Key-Management.json",
  "Name": "did:keri",
  "Implementation Support": "https://weboftrust.github.io/did-keri/",
  "Infrastructure for Key Resolution": {
    "Value": true,
    "Description": "witness network"
  },
  "Key Rotation": true,
  "Key History": true,
  "Party": ["holder", "issuer"]
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Key-Management/did.web.json
{
  "$schema": "../../schemas/Key-Management.json",
  "Name": "did:web",
  "Implementation Support": "https://github.com/w3c-ccg/did-method-web",
  "Infrastructure for Key Resolution": {
    "Value": true,
    "Description": "web server"
  },
  "Key Rotation": true,
  "Key History": false,
  "Party": ["holder", "issuer"]
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/Key-Management/raw-public-keys-(jwk).json
{
  "$schema": "../../schemas/Key-Management.json",
  "Name": "raw public keys (jwk)",
  "Implementation Support": "https://www.rfc-editor.org/rfc/rfc7517",
  "IPR Policy": "https://trustee.ietf.org/documents/trust-legal-provisions/",
  "Specification": "https://www.rfc-editor.org/rfc/rfc7517",
  "Infrastructure for Key Resolution": false,
  "Key Rotation": false,
  "Key History": {
    "Value": true,
    "Description": "conditional (with OpenID Connect Federation Key History)"
  },
  "Party": ["holder", "issuer"]
}
