=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/schemas/wallet.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Wallet",
  "title": "Wallet or Agent",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version of the agent JSON entry"
    },
    "name": {
      "type": "string",
      "description": "The name of the agent"
    },
    "urlWebsite": {
      "type": "string",
      "description": "An URL to the website of the agent with more information",
      "format": "uri"
    },
    "logo": {
      "type": "string",
      "description": "The URL to the logo of the agent"
    },
    "company": {
      "type": "string",
      "description": "The name of the company or a community developing the agent"
    },
    "companyUrl": {
      "type": "string",
      "description": "The url to the company website (not the product website)",
      "format": "uri"
    },
    "contact": {
      "type": "string",
      "description": "A link to a contact form or an email address for support requests"
    },
    "openSource": {
      "type": "boolean",
      "description": "The agent source code is available under an open-source license"
    },
    "downloadSource": {
      "type": "string",
      "description": "The URL to the source code, for example a github repository",
      "format": "uri"
    },
    "license": {
      "type": "string",
      "description": "The license(s) of the agent source code."
    },
    "capability": {
      "type": "array",
      "description": "The capabilities supported by the agent",
      "items": {
        "type": "string",
        "enum": ["holder", "issuer", "verifier"]
      }
    },
    "executionEnvironment":  {
      "type": "string",
      "description": "Execution environment of an agent is the place where the agent is intended to be run",
      "enum": ["cloud", "edge"]
    },
    "portability": {
      "type": "boolean",
      "description": "Users can export their data from the agent and import them into another device/system"
    },
    "urlAppStore": {
      "type": "string",
      "description": "Link to the Apple AppStore",
      "format": "uri"
    },
    "urlGooglePlayStore": {
      "type": "string",
      "description": "Link to the Google Play store",
      "format": "uri"
    },
    "urlWebApp": {
      "type": "string",
      "description": "Link to the web app - where the agent can be used with a browser",
      "format": "uri"
    },
    "dependencies": {
      "type": "array",
      "description": "List of dependencies required to run the agent",
      "items": {
        "$comment": "it would help to use an enum here, but this job has to be run by each change so the enum gets updated for a valid test.",
        "type": "string"
      }
    },
    "credentialProfiles": {
      "type": "array",
      "description": "List of supported credential profiles. They entries must be valid credential profiles defined by the Credential Profiles Comparison SIG.",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/",
      "items": {
        "type": "string"
      }
    },
    "credentialFormats": {
      "type": "array",
      "description": "List of supported credential formats. They entries must be valid credential formats defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Credential%20Format",
      "items": {
        "type": "string"
      }
    },
    "signingAlgorithms": {
      "type": "array",
      "description": "List of supported signing algorithms. The entries must be valid algorithms defined by the Credential Formats Comparison SIG.",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Signing%20Algorithm",
      "items": {
        "type": "string"
      }
    },
    "statusManagements": {
      "type": "array",
      "description": "List of supported status management methods. The entries must be valid status management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Status%20Algorithm",
      "items": {
        "type": "string"
      }
    },
    "keyManagements": {
      "type": "array",
      "description": "List of supported key management methods. The entries must be valid key management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Key%20Management",
      "items": {
        "type": "string"
      }
    },
    "issuanceProtocols": {
      "type": "array",
      "description": "List of supported issuance protocols. The entries must be valid issuance protocols defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Issuance%20Protocol",
      "items": {
        "type": "string"
      }
    },
    "presentationProtocols": {
      "type": "array",
      "description": "List of supported presentation protocols. The entries must be valid presentation protocols defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Presentation%20Protocol",
      "items": {
        "type": "string"
      }
    },
    "trustManagements": {
      "type": "array",
      "description": "List of supported trust management methods. The entries must be valid trust management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Trust%20Management",
      "items": {
        "type": "string"
      }
    }
  },
  "required": ["capability", "company", "name", "urlWebsite"],
  "additionalProperties": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/zada.json
{
  "capability": ["holder"],
  "company": "ZADA Solutions",
  "credentialFormats": ["AnonCred"],
  "credentialProfiles": ["AnonCreds with did:indy"],
  "downloadSource": "https://github.com/lycheeventures/zada-wallet",
  "license": "CC BY NC SA",
  "logo": "logos/zada.png",
  "name": "ZADA",
  "openSource": true,
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["CL", "RSA"],
  "statusManagements": ["Indy Revocation"],
  "executionEnvironment": "edge",
  "urlAppStore": "https://apps.apple.com/us/app/zada-wallet/id1578666669",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=com.zadanetwork.wallet",
  "urlWebsite": "https://zada.io/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/wwwallet.json
{
  "capability": ["holder"],
  "company": "GUnet",
  "credentialFormats": ["JWT-VC"],
  "credentialProfiles": ["EBSI"],
  "downloadSource": "https://github.com/wwWallet",
  "logo": "logos/wwwallet.png",
  "name": "wwWallet",
  "openSource": true,
  "$schema": "../../schemas/wallet.json",
  "executionEnvironment": "cloud",
  "urlWebApp": "https://demo.wwwallet.org/",
  "urlWebsite": "https://wwwallet.github.io/wallet-docs/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/spherity-wallet.json
{
  "capability": ["issuer", "holder", "verifier"],
  "company": "Spherity GmbH",
  "credentialFormats": ["LDP-VC"],
  "issuanceProtocols": ["Issue Credential v3"],
  "logo": "logos/spherity-wallet.png",
  "name": "Spherity Wallet",
  "openSource": false,
  "presentationProtocols": ["Presentation Exchange v1"],
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["BBS+ with public key binding", "ECDSA", "EdDSA", "RSA"],
  "statusManagements": ["Status List 2021"],
  "executionEnvironment":"cloud",
  "urlWebsite": "https://www.spherity.com/enterprise-identity-wallet"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/vidwallet.json
{
  "capability": ["holder"],
  "company": "Validated ID",
  "credentialFormats": ["JWT-VC", "LDP-VC", "JWT"],
  "issuanceProtocols": ["OpenID4VCI"],
  "keyManagements": ["did:key", "did:jwk", "did:ebsi"],
  "logo": "logos/VIDwallet.png",
  "name": "VIDwallet",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["ECDSA", "EdDSA"],
  "statusManagements": ["Status List 2021"],
  "executionEnvironment":"edge",
  "urlAppStore": "https://apps.apple.com/si/app/vidwallet/id1554340592",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=com.validatedid.wallet&hl=en_US&gl=US",
  "urlWebsite": "https://www.validatedid.com/en/vidchain/vidwallet"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/holdr.json
{
  "capability": ["holder"],
  "company": "Indicio",
  "credentialFormats": ["AnonCred"],
  "credentialProfiles": ["AnonCreds with did:indy"],
  "logo": "logos/holdr.png",
  "name": "Holdr+",
  "$schema": "../../schemas/wallet.json",
  "executionEnvironment": "edge",
  "urlAppStore": "https://apps.apple.com/us/app/holdr/id1620628623",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=tech.indicio.holdrplus",
  "urlWebsite": "https://indicio.tech/holdr/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/dock-wallet.json
{
  "capability": ["holder"],
  "company": "Dock",
  "contact": "marketing@dock.io",
  "downloadSource": "https://github.com/docknetwork/universal-wallet",
  "name": "Dock Wallet",
  "$schema": "../../schemas/wallet.json",
  "executionEnvironment": "edge",
  "urlAppStore": "https://apps.apple.com/ph/app/dock-wallet/id1565227368",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=com.dockapp",
  "urlWebsite": "https://www.dock.io/dock-wallet-app"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/entidad-unmio-mobile.json
{
  "capability": [
    "holder"
  ],
  "executionEnvironment":"edge",
  "name": "Unmio mobile",
  "logo": "https://unmio-ecosystem-assets.s3.us-west-1.amazonaws.com/images/Unmio_Logo_Green-Color.png",
  "company": "Entidad",
  "companyUrl": "https://www.entidad.io",
  "contact": "info@unmio.com",
  "urlWebsite": "https://www.unmio.com",
  "urlAppStore": "https://apps.apple.com/us/app/unmio/id6581480643",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=io.entidad.app.unmio",
  "openSource": false,
  "license": "Commercial",
  "portability": false,
  "credentialProfiles": [
    "AnonCreds with did:indy",
    "AnonCreds with did:web"
  ],
  "credentialFormats": [
    "AnonCred"
  ],
  "issuanceProtocols": [
    "Issue Credential v2"
  ],
  "keyManagements": [
    "did:indy",
    "did:jwk",
    "did:key",
    "did:peer",
    "did:web",
    "raw public keys (jwk)"
  ],
  "presentationProtocols": [
    "Present Proof v2",
    "Present Proof v1.0"
  ],
  "dependencies": [
    "credo",
    "farmworker-wallet-os"
  ],
  "signingAlgorithms": [
    "CL",
    "ECDSA",
    "EdDSA"
  ],
  "statusManagements": [
    "Indy Revocation"
  ],
  "trustManagements": [],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/sovio-platform.json
{
    "$schema": "../../schemas/wallet.json",
    "capability": [
        "issuer",
        "holder",
        "verifier"
    ],
   "logo": "https://www.ayanworks.com/assets/Landing%20Page/sovio-Wallet%201.svg",
   "company": "AYANWORKS",
   "companyUrl": "https://www.ayanworks.com",
   "urlWebsite": "https://sovio.id/",
    "credentialFormats": [
        "AnonCred",
        "MDOC",
        "SD-JWT",
        "VCDM 1.1"
    ],
    "credentialProfiles": [
        "AnonCreds with did:indy",
        "AnonCreds with did:web",
        "ISO mDL",
        "JWT VC Presentation Profile 2",
        "SD-JWT VCs (w/ X.509 for Issuers)",
        "JSON-LD Verifiable Credentials with secp256k1"
    ],
    "issuanceProtocols": [
        "Issue Credential v2",
        "OpenID4VCI"
    ],
    "keyManagements": [
        "did:indy",
        "did:key",
        "did:peer",
        "did:web",
        "did:polygon",
        "pub key in X.509 cert"
    ],
    "license": "Apache-2.0 license",
    "name": "CREDEBL Platform",
    "openSource": false,
    "portability": true,
    "presentationProtocols": [
        "OpenID4VP",
        "Present Proof v2"
    ],
    "signingAlgorithms": [
        "CL",
        "ECDSA",
        "EdDSA"
    ],
    "statusManagements": [
        "Indy Revocation"
    ],
    "trustManagements": [
        "X.509 certificates"
    ],
    "dependencies": [
        "credo"
    ]
}
