=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/schemas/wallet.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Wallet",
  "title": "Wallet or Agent",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version of the agent JSON entry"
    },
    "name": {
      "type": "string",
      "description": "The name of the agent"
    },
    "urlWebsite": {
      "type": "string",
      "description": "An URL to the website of the agent with more information",
      "format": "uri"
    },
    "logo": {
      "type": "string",
      "description": "The URL to the logo of the agent"
    },
    "company": {
      "type": "string",
      "description": "The name of the company or a community developing the agent"
    },
    "companyUrl": {
      "type": "string",
      "description": "The url to the company website (not the product website)",
      "format": "uri"
    },
    "contact": {
      "type": "string",
      "description": "A link to a contact form or an email address for support requests"
    },
    "openSource": {
      "type": "boolean",
      "description": "The agent source code is available under an open-source license"
    },
    "downloadSource": {
      "type": "string",
      "description": "The URL to the source code, for example a github repository",
      "format": "uri"
    },
    "license": {
      "type": "string",
      "description": "The license(s) of the agent source code."
    },
    "capability": {
      "type": "array",
      "description": "The capabilities supported by the agent",
      "items": {
        "type": "string",
        "enum": ["holder", "issuer", "verifier"]
      }
    },
    "executionEnvironment":  {
      "type": "string",
      "description": "Execution environment of an agent is the place where the agent is intended to be run",
      "enum": ["cloud", "edge"]
    },
    "portability": {
      "type": "boolean",
      "description": "Users can export their data from the agent and import them into another device/system"
    },
    "urlAppStore": {
      "type": "string",
      "description": "Link to the Apple AppStore",
      "format": "uri"
    },
    "urlGooglePlayStore": {
      "type": "string",
      "description": "Link to the Google Play store",
      "format": "uri"
    },
    "urlWebApp": {
      "type": "string",
      "description": "Link to the web app - where the agent can be used with a browser",
      "format": "uri"
    },
    "dependencies": {
      "type": "array",
      "description": "List of dependencies required to run the agent",
      "items": {
        "$comment": "it would help to use an enum here, but this job has to be run by each change so the enum gets updated for a valid test.",
        "type": "string"
      }
    },
    "credentialProfiles": {
      "type": "array",
      "description": "List of supported credential profiles. They entries must be valid credential profiles defined by the Credential Profiles Comparison SIG.",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/",
      "items": {
        "type": "string"
      }
    },
    "credentialFormats": {
      "type": "array",
      "description": "List of supported credential formats. They entries must be valid credential formats defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Credential%20Format",
      "items": {
        "type": "string"
      }
    },
    "signingAlgorithms": {
      "type": "array",
      "description": "List of supported signing algorithms. The entries must be valid algorithms defined by the Credential Formats Comparison SIG.",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Signing%20Algorithm",
      "items": {
        "type": "string"
      }
    },
    "statusManagements": {
      "type": "array",
      "description": "List of supported status management methods. The entries must be valid status management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Status%20Algorithm",
      "items": {
        "type": "string"
      }
    },
    "keyManagements": {
      "type": "array",
      "description": "List of supported key management methods. The entries must be valid key management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Key%20Management",
      "items": {
        "type": "string"
      }
    },
    "issuanceProtocols": {
      "type": "array",
      "description": "List of supported issuance protocols. The entries must be valid issuance protocols defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Issuance%20Protocol",
      "items": {
        "type": "string"
      }
    },
    "presentationProtocols": {
      "type": "array",
      "description": "List of supported presentation protocols. The entries must be valid presentation protocols defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Presentation%20Protocol",
      "items": {
        "type": "string"
      }
    },
    "trustManagements": {
      "type": "array",
      "description": "List of supported trust management methods. The entries must be valid trust management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Trust%20Management",
      "items": {
        "type": "string"
      }
    }
  },
  "required": ["capability", "company", "name", "urlWebsite"],
  "additionalProperties": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/selfkey-wallet.json
{
  "capability": ["holder"],
  "company": "SelfKey",
  "downloadSource": "https://github.com/SelfKeyFoundation/Identity-Wallet",
  "license": "MIT",
  "name": "SelfKey Wallet",
  "$schema": "../../schemas/wallet.json",
  "executionEnvironment": "edge",
  "urlAppStore": "https://selfkey.org/selfkey-wallet-ios-download",
  "urlGooglePlayStore": "https://selfkey.org/selfkey-wallet-android-download",
  "urlWebsite": "https://selfkey.org/selfkey-wallet/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/walt.id.json
{
  "capability": ["holder", "issuer", "verifier"],
  "company": "walt.id",
  "credentialFormats": ["JWT", "LDP-VC", "SD-JWT"],
  "credentialProfiles": ["EBSI"],
  "downloadSource": "https://github.com/walt-id/waltid-identity",
  "issuanceProtocols": ["OpenID4VCI"],
  "keyManagements": ["did:key", "did:web", "did:ebsi", "did:jwk", "did:cheqd"],
  "license": "Apache 2.0",
  "logo": "logos/walt-id.png",
  "name": "walt.id",
  "openSource": true,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["ECDSA", "EdDSA", "RSA"],
  "statusManagements": ["Status List 2021"],
  "executionEnvironment": "cloud",
  "urlWebApp": "https://wallet.walt.id/",
  "urlWebsite": "https://walt.id/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/hightrust.id.json
{
  "name": "hightrust.id",
  "logo": "logos/hightrust.png",
  "company": "Megical Oy",
  "executionEnvironment": "edge",
  "openSource": false,
  "license": "Commercial software license",
  "capability": ["holder"],
  "credentialProfiles": [],
  "credentialFormats": [],
  "issuanceProtocols": [],
  "keyManagements": [],
  "presentationProtocols": [],
  "signingAlgorithms": [],
  "statusManagements": [],
  "trustManagements": [],
  "urlAppStore": "https://apps.apple.com/fi/app/hightrust-id/id1549852126",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=com.megical.easyaccess",
  "urlWebsite": "https://www.hightrust.id",
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/entidad-unmio.json
{
  "capability": [
    "issuer",
    "verifier"
  ],
  "executionEnvironment": "cloud",
  "name": "Unmio",
  "logo": "https://unmio-ecosystem-assets.s3.us-west-1.amazonaws.com/images/Unmio_Logo_Green-Color.png",
  "company": "Entidad",
  "companyUrl": "https://www.entidad.io",
  "contact": "info@unmio.com",
  "urlWebsite": "https://www.unmio.com",
  "openSource": false,
  "license": "Commercial",
  "portability": false,
  "credentialProfiles": [
    "AnonCreds with did:indy",
    "AnonCreds with did:web"
  ],
  "credentialFormats": [
    "AnonCred"
  ],
  "issuanceProtocols": [
    "Issue Credential v2"
  ],
  "keyManagements": [
    "did:key",
    "did:web",
    "did:peer"
  ],
  "presentationProtocols": [
    "Present Proof v2",
    "Present Proof v1.0"
  ],
  "dependencies": [
    "farmworker-wallet-os"
  ],
  "signingAlgorithms": [
    "CL",
    "ECDSA",
    "EdDSA"
  ],
  "statusManagements": [
    "Indy Revocation"
  ],
  "trustManagements": [],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/authenticator.json
{
  "capability": ["holder"],
  "company": "Microsoft",
  "credentialFormats": ["JWT-VC"],
  "keyManagements": ["did:web"],
  "logo": "logos/authenticator.png",
  "name": "Authenticator",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "executionEnvironment": "edge",
  "urlAppStore": "https://go.microsoft.com/fwlink/p/?linkid=2168643&clcid=0x409",
  "urlGooglePlayStore": "https://go.microsoft.com/fwlink/p/?linkid=2168850&clcid=0x409",
  "urlWebsite": "https://www.microsoft.com/en-us/security/mobile-authenticator-app"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/sowl.json
{
  "capability": ["issuer", "verifier"],
  "company": "esatus AG",
  "credentialFormats": ["AnonCred"],
  "credentialProfiles": ["AnonCreds with did:indy"],
  "logo": "logos/esatus-wallet.png",
  "name": "SOWL",
  "$schema": "../../schemas/wallet.json",
  "executionEnvironment": "cloud",
  "urlWebsite": "https://esatus.com/en/digital-identity/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/vidua.json
{
  "capability": ["holder"],
  "company": "Cleverbase",
  "credentialFormats": ["x509", "JWT"],
  "contact": "klantenservice@vidua.nl",
  "issuanceProtocols": ["OpenID4VCI"],
  "logo": "logos/vidua.png",
  "name": "Vidua",
  "openSource": false,
  "portability": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["ECDSA", "RSA"],
  "executionEnvironment": "edge",
  "urlAppStore": "https://apps.apple.com/en/app/vidua/id6443842104",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=nl.vidua.wallet",
  "urlWebsite": "https://vidua.nl/english/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/anonyome-wallet.json
{
  "capability": ["holder"],
  "executionEnvironment":"edge",
  "name": "Anonyome Mobile Wallet",
  "logo": "logos/anonyome.png",
  "company": "Anonyome Labs",
  "companyUrl": "https://www.anonyome.com",
  "urlWebsite": "https://sudoplatform.com/identity-wallet/",
  "openSource": false,
  "license": "",
  "credentialProfiles": ["AnonCreds with did:indy"],
  "credentialFormats": ["AnonCred", "LDP-VC", "VC (1.1)", "SD-JWT-VC", "SD-JWT"],
  "issuanceProtocols": ["Issue Credential v1", "Issue Credential v2", "OpenID4VCI"],
  "keyManagements": ["did:indy", "did:key", "did:peer", "link secrets"],
  "presentationProtocols": ["Present Proof v2", "Present Proof v1.0", "OpenID4VP"],
  "signingAlgorithms": ["BBS+ with public key binding", "CL", "ECDSA", "EdDSA"],
  "statusManagements": ["Indy Revocation"],
  "trustManagements": [],
  "$schema": "../../schemas/wallet.json"
}
