=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/schemas/wallet.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Wallet",
  "title": "Wallet or Agent",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version of the agent JSON entry"
    },
    "name": {
      "type": "string",
      "description": "The name of the agent"
    },
    "urlWebsite": {
      "type": "string",
      "description": "An URL to the website of the agent with more information",
      "format": "uri"
    },
    "logo": {
      "type": "string",
      "description": "The URL to the logo of the agent"
    },
    "company": {
      "type": "string",
      "description": "The name of the company or a community developing the agent"
    },
    "companyUrl": {
      "type": "string",
      "description": "The url to the company website (not the product website)",
      "format": "uri"
    },
    "contact": {
      "type": "string",
      "description": "A link to a contact form or an email address for support requests"
    },
    "openSource": {
      "type": "boolean",
      "description": "The agent source code is available under an open-source license"
    },
    "downloadSource": {
      "type": "string",
      "description": "The URL to the source code, for example a github repository",
      "format": "uri"
    },
    "license": {
      "type": "string",
      "description": "The license(s) of the agent source code."
    },
    "capability": {
      "type": "array",
      "description": "The capabilities supported by the agent",
      "items": {
        "type": "string",
        "enum": ["holder", "issuer", "verifier"]
      }
    },
    "executionEnvironment":  {
      "type": "string",
      "description": "Execution environment of an agent is the place where the agent is intended to be run",
      "enum": ["cloud", "edge"]
    },
    "portability": {
      "type": "boolean",
      "description": "Users can export their data from the agent and import them into another device/system"
    },
    "urlAppStore": {
      "type": "string",
      "description": "Link to the Apple AppStore",
      "format": "uri"
    },
    "urlGooglePlayStore": {
      "type": "string",
      "description": "Link to the Google Play store",
      "format": "uri"
    },
    "urlWebApp": {
      "type": "string",
      "description": "Link to the web app - where the agent can be used with a browser",
      "format": "uri"
    },
    "dependencies": {
      "type": "array",
      "description": "List of dependencies required to run the agent",
      "items": {
        "$comment": "it would help to use an enum here, but this job has to be run by each change so the enum gets updated for a valid test.",
        "type": "string"
      }
    },
    "credentialProfiles": {
      "type": "array",
      "description": "List of supported credential profiles. They entries must be valid credential profiles defined by the Credential Profiles Comparison SIG.",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/",
      "items": {
        "type": "string"
      }
    },
    "credentialFormats": {
      "type": "array",
      "description": "List of supported credential formats. They entries must be valid credential formats defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Credential%20Format",
      "items": {
        "type": "string"
      }
    },
    "signingAlgorithms": {
      "type": "array",
      "description": "List of supported signing algorithms. The entries must be valid algorithms defined by the Credential Formats Comparison SIG.",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Signing%20Algorithm",
      "items": {
        "type": "string"
      }
    },
    "statusManagements": {
      "type": "array",
      "description": "List of supported status management methods. The entries must be valid status management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Status%20Algorithm",
      "items": {
        "type": "string"
      }
    },
    "keyManagements": {
      "type": "array",
      "description": "List of supported key management methods. The entries must be valid key management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Key%20Management",
      "items": {
        "type": "string"
      }
    },
    "issuanceProtocols": {
      "type": "array",
      "description": "List of supported issuance protocols. The entries must be valid issuance protocols defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Issuance%20Protocol",
      "items": {
        "type": "string"
      }
    },
    "presentationProtocols": {
      "type": "array",
      "description": "List of supported presentation protocols. The entries must be valid presentation protocols defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Presentation%20Protocol",
      "items": {
        "type": "string"
      }
    },
    "trustManagements": {
      "type": "array",
      "description": "List of supported trust management methods. The entries must be valid trust management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Trust%20Management",
      "items": {
        "type": "string"
      }
    }
  },
  "required": ["capability", "company", "name", "urlWebsite"],
  "additionalProperties": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/authada.json
{
  "capability": [
    "issuer",
    "verifier"
  ],
  "name": "AUTHADA wallet platform",
  "logo": "https://authada.de/wp-content/uploads/2022/02/authada-logo.svg",
  "company": "AUTHADA GmbH",
  "companyUrl": "https://authada.de/",
  "urlWebsite": "https://authada.de/loesungen/wallet-platform/",
  "openSource": false,
  "portability": false,
  "credentialProfiles": [
    "HAIP",
    "ISO mDL",
    "SD-JWT VCs (w/ X.509 for Issuers)",
    "x.509"
  ],
  "credentialFormats": [
    "MDOC",
    "SD-JWT VC",
    "x509"
  ],
  "issuanceProtocols": [
    "OpenID4VCI"
  ],
  "keyManagements": [
    "jwks_uri",
    "pub key in X.509 cert",
    "raw public keys (jwk)"
  ],
  "presentationProtocols": [
    "OpenID4VP"
  ],
  "signingAlgorithms": [
    "ECDSA"
  ],
  "statusManagements": [
    "Token Status List (TSL)"
  ],
  "trustManagements": [
    "Trusted Lists",
    "Verified issuer certificate authority list (VICAL)",
    "X.509 certificates"
  ],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/vidos-id.json
{
    "capability": [
      "verifier"
    ],
    "executionEnvironment": "cloud",
    "name": "Vidos Verifier",
    "logo": "https://vidos-id.github.io/static-assets/openwallet_foundation/vidos-logo-onwhite.png",
    "company": "Vidos",
    "companyUrl": "https://vidos.id",
    "urlWebsite": "https://vidos.id",
    "urlWebApp": "https://vidos.id",
    "openSource": false,
    "license": "Commercial SaaS",
    "portability": false,
    "credentialProfiles": [
      "JSON-LD VCs with BBS (Credential is Secret)",
      "JSON-LD VCs with BBS (Holder DID)"
    ],
    "credentialFormats": [
      "JWT-VC",
      "JWT",
      "LDP-VC",
      "VC (1.1)"
    ],
    "issuanceProtocols": [],
    "keyManagements": [
      "did:cheqd",
      "did:ebsi",
      "did:ion (long form)",
      "did:jwk",
      "did:key",
      "did:peer",
      "did:web"
    ],
    "presentationProtocols": [],
    "signingAlgorithms": [
      "BBS+ with public key binding",
      "ECDSA",
      "EdDSA",
      "RSA",
      "Schnorr"
    ],
    "statusManagements": [
      "Status List 2021"
    ],
    "trustManagements": [],
    "$schema": "../viewer/src/assets/schema.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/gataca-studio.json
{
  "capability": ["issuer", "verifier"],
  "company": "Gataca Inc.",
  "credentialFormats": ["LDP-VC", "JWT-VC"],
  "credentialProfiles": ["EBSI"],
  "issuanceProtocols": ["OpenID4VCI"],
  "keyManagements": ["did:key"],
  "logo": "logos/gataca.png",
  "name": "Gataca Studio",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["EdDSA", "RSA"],
  "statusManagements": ["Status List 2021"],
  "executionEnvironment": "cloud",
  "urlWebsite": "https://gataca.io/products/gatacaStudio/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/paradym-wallet.json
{
  "capability": ["holder"],
  "company": "Animo Solutions",
  "contact": "ana@animo.id",
  "credentialFormats": ["JWT-VC", "AnonCred", "SD-JWT-VC"],
  "downloadSource": "https://github.com/animo/paradym-wallet",
  "issuanceProtocols": ["OpenID4VCI", "Issue Credential v2"],
  "keyManagements": ["did:jwk", "did:key", "did:web", "did:cheqd", "did:indy"],
  "logo": "logos/paradym-wallet.png",
  "name": "Paradym Wallet",
  "openSource": true,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["EdDSA", "ECDSA"],
  "executionEnvironment":"edge",
  "license": "Apache 2.0",
  "statusManagements": ["Indy Revocation", "JWT/CWT status list"],
  "dependencies": ["credo", "sd-jwt-js"],
  "credentialProfiles": [
    "AnonCreds with did:cheqd",
    "AnonCreds with did:indy",
    "Decentralized Identity Interop Profile"
  ],
  "urlAppStore": "https://apps.apple.com/nl/app/paradym-wallet/id6449846111?l=en",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=id.paradym.wallet",
  "urlWebsite": "https://docs.paradym.id/integrating-with-a-holder-wallet/paradym-wallet"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/helix-id.json
{
  "capability": ["holder"],
  "company": "Blockchain Helix AG",
  "credentialFormats": ["JWT", "JWT-VC"],
  "issuanceProtocols": ["OpenID4VCI", "Issue Credential v2"],
  "keyManagements": ["did:key"],
  "logo": "logos/helix-id.png",
  "name": "helix id",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["BBS+ with public key binding", "ECDSA"],
  "executionEnvironment":"edge",
  "urlAppStore": "https://apps.apple.com/de/app/helix-id-wallet/id1469238013",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=com.io.helix.id",
  "urlWebsite": "https://helixid.io/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/esatus-wallet.json
{
  "capability": ["holder"],
  "company": "esatus AG",
  "credentialFormats": ["AnonCred"],
  "credentialProfiles": ["AnonCreds with did:indy"],
  "issuanceProtocols": ["Issue Credential v2"],
  "logo": "logos/esatus-wallet.png",
  "name": "esatus Wallet",
  "openSource": false,
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["CL"],
  "statusManagements": ["Indy Revocation"],
  "executionEnvironment": "edge",
  "urlAppStore": "https://apps.apple.com/us/app/esatus-wallet/id1496769057?itsct=apps_box&itscg=30200",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=com.esatus.wallet&hl=de_DE&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1",
  "urlWebsite": "https://esatus.com/index.html%3Fp=7663&lang=en.html"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/farmworker-wallet-os.json
{
  "capability": [
    "holder"
  ],
  "executionEnvironment":"edge",
  "name": "Farmworker Wallet OS",
  "logo": "https://cdn.prod.website-files.com/6520979d785cc136404a270d/65237d6a3505e25d76ed58c7_wallet-p-1080.png",
  "company": " Entidad",
  "companyUrl": "https://www.entidad.io",
  "urlWebsite": "https://www.farmworkerwalletos.community/",
  "downloadSource": "https://github.com/openwallet-foundation-labs/farmworker-wallet-os",
  "openSource": true,
  "license": "Apache 2.0",
  "portability": false,
  "credentialProfiles": [
    "AnonCreds with did:indy",
    "AnonCreds with did:web"
  ],
  "credentialFormats": [
    "AnonCred"
  ],
  "issuanceProtocols": [],
  "keyManagements": [
    "did:indy",
    "did:jwk",
    "did:key",
    "did:peer",
    "did:web",
    "raw public keys (jwk)"
  ],
  "presentationProtocols": [
    "Present Proof v2",
    "Present Proof v1.0"
  ],
  "signingAlgorithms": [
    "CL",
    "ECDSA",
    "EdDSA"
  ],
  "statusManagements": [],
  "trustManagements": [],
  "dependencies": [
    "credo"
  ],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/microsoft-entra.json
{
  "capability": ["issuer", "verifier"],
  "company": "Microsoft",
  "credentialFormats": ["JWT-VC"],
  "keyManagements": ["did:web"],
  "logo": "logos/microsoft-entra.png",
  "name": "Microsoft Entra Verified ID",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "statusManagements": ["Status List 2021"],
  "executionEnvironment":"cloud",
  "urlWebsite": "https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-verified-id"
}
